export const FONT_OPTIONS = [
  { id: "", label: "Theme Default" },
  // Sans-serif
  { id: "'Inter', sans-serif", label: "Inter" },
  { id: "'DM Sans', sans-serif", label: "DM Sans" },
  { id: "'Outfit', sans-serif", label: "Outfit" },
  { id: "'Space Grotesk', sans-serif", label: "Space Grotesk" },
  { id: "'Arimo', sans-serif", label: "Arimo" },
  { id: "'Clear Sans', sans-serif", label: "Clear Sans" },
  { id: "'Nunito Sans', sans-serif", label: "Nunito Sans" },
  { id: "'Open Sans', sans-serif", label: "Open Sans" },
  { id: "'Lato', sans-serif", label: "Lato" },
  { id: "'Rubik', sans-serif", label: "Rubik" },
  // Monospace / Coding
  { id: "'JetBrains Mono', monospace", label: "JetBrains Mono" },
  { id: "'Fira Code', monospace", label: "Fira Code" },
  { id: "'Source Code Pro', monospace", label: "Source Code Pro" },
  { id: "'IBM Plex Mono', monospace", label: "IBM Plex Mono" },
  { id: "'Space Mono', monospace", label: "Space Mono" },
  { id: "'Roboto Mono', monospace", label: "Roboto Mono" },
  { id: "'Inconsolata', monospace", label: "Inconsolata" },
  { id: "'DM Mono', monospace", label: "DM Mono" },
  { id: "'Ubuntu Mono', monospace", label: "Ubuntu Mono" },
  { id: "'Hack', monospace", label: "Hack" },
  { id: "'Anonymous Pro', monospace", label: "Anonymous Pro" },
  { id: "'Cousine', monospace", label: "Cousine" },
  { id: "'PT Mono', monospace", label: "PT Mono" },
  { id: "'Overpass Mono', monospace", label: "Overpass Mono" },
  { id: "'Noto Sans Mono', monospace", label: "Noto Sans Mono" },
  { id: "'Red Hat Mono', monospace", label: "Red Hat Mono" },
  { id: "'Martian Mono', monospace", label: "Martian Mono" },
];
